### PR TITLE
Profile Page User Interface

### PR DESCRIPTION
**Pull request by shiara02**
### OVERVIEW

Create the UI of Profile Page (Navbar, Create Post, View User/Self post).

### NOTES

None.

### SNIPPETS

image
image

### CODE REVIEW

**Comment by bpocrafael** [comment]
fix conflicts

**Review by hipe-francis — DISMISSED** [review]
LGTM 🚀

**Comment by hipe-francis** [comment]
Fix conflicts on your web.php file, it seems that it was included in your PR.

**Review by bpocrafael — APPROVED** [review]

**Review by hipe-francis — APPROVED** [review]
LGTM 🚀

**Pull request merged**
